### ISSUE TITLE
Had troubles installing the package with use_NVIverse(pkg = c("OKplan"))

### ISSUE THREAD

**Issue by JohanAkerstedt** [NorwegianVeterinaryInstitute/OKplan#5]
Used the following and it worked fine:
# To install (or update) the OKplan package, run the following code:
remotes::install_github("NorwegianVeterinaryInstitute/OKplan",
                        upgrade = FALSE,
                        build = TRUE,
                        build_manual = TRUE)

**Comment by PetterHopp** [comment]
fixed in NVIbatch v0.2.3 with updated use_NVIverse
